community/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.post_list, name="post_list"),
    ### post
    path("post/write/", views.post_write, name="post_write"),
    path("<int:post_id>/", views.post_detail, name="post_detail"),
    path("post/edit/<int:post_id>/", views.post_edit, name="post_edit"),
    path("post/delete/<int:post_id>/", views.post_delete, name="post_delete"),
    # path("post/like/", views.post_like, name='post_like'),
    ### answer
    path("answer/write/<int:post_id>/", views.answer_write, name="answer_write"),
    path("answer/edit/<int:answer_id>/", views.answer_edit, name="answer_edit"),
    path("answer/delete/<int:answer_id>/", views.answer_delete, name="answer_delete"),
    ### comment
    path(
        "comment/write/answer/<int:answer_id>/",
        views.comment_write,
        name="comment_write",
    ),
    path(
        "comment/edit/answer/<int:comment_id>/", views.comment_edit, name="comment_edit"
    ),
    path(
        "comment/delete/answer/<int:comment_id>/",
        views.comment_delete,
        name="comment_delete",
    ),
    ### vote
    # http://127.0.0.1:8000/board/question/vote/1/
    path("question/vote/<int:post_id>/", views.vote_post, name="vote_post"),
    path("answer/vote/<int:answer_id>/", views.vote_answer, name="vote_answer"),
    path("comment/vote/<int:comment_id>/", views.vote_comment, name="vote_comment"),
    
]

community/models.py
from django.db import models
from user.models import User
from django.db.models import UniqueConstraint
from django.template.defaultfilters import slugify
from django.urls import reverse

class BaseModel(models.Model):
    created_at = models.DateTimeField(verbose_name='작성날짜', auto_now_add=True)
    modified_at = models.DateTimeField(verbose_name='수정날짜', auto_now=True)
    
    class Meta:
        abstract = True
    
    
class Post(BaseModel):
    title = models.CharField(max_length=200, verbose_name='제목')
    writer = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='작성자', related_name='writer_post')
    content = models.TextField(verbose_name='내용')
    view_cnt = models.BigIntegerField(default=0)
    vote = models.ManyToManyField(User, related_name='vote_post', verbose_name='추천수')
    
    def __str__(self) -> str:
        return self.title
    
    def get_absolute_url(self):
        return reverse("post_detail", args=[self.pk])
    
    def get_previous(self):
        return self.get_previous_by_created_at()
    
    def get_next(self):
        return self.get_next_by_created_at()
    
    
# image file naming
# instance => 현재 정의된 모델의 인스턴스 
# filename => 파일에 원래 제공된 파일 이름. 이것은 최종 목적지 경로를 결정할 때 고려되거나 고려되지 않을 수 있음
def image_upload_to(instance, filename):
    # 해당 Post 모델의 title 을 가져옴
    title = instance.post.title
    # slug - 의미있는 url 사용을 위한 필드.
    # slugfy 를 사용해서 title을 slug 시켜줌.
    slug = slugify(title)
    # 제목 - 슬러그된 파일이름 형태
    return "post_images/%s-%s" % (slug, filename)


class Image(BaseModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name="작성글", related_name="image")
    image = models.ImageField(upload_to=image_upload_to)

    class Meta:
        # 단수
        verbose_name = 'Image'
        # 복수
        verbose_name_plural = 'Images'

    # 이것도 역시 post title 로 반환
    def __str__(self):
       return str(self.post)


class PostCount(models.Model):
    ip = models.CharField(max_length=30)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    
    def __unicode__(self):
        return self.ip
    
    
class Answer(BaseModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField(verbose_name='댓글')
    writer = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='작성자', related_name='writer_answer')
    vote = models.ManyToManyField(User, related_name='vote_answer', verbose_name='추천수')
    
    
class Comment(BaseModel):
    writer = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='작성자',related_name='writer_comment')
    content = models.TextField(verbose_name='대댓글')
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, null=True, blank=True)
    vote = models.ManyToManyField(User, related_name='vote_comment', verbose_name='추천수')

templates/answer_form.html
{% extends 'base.html' %}
{% block contents %}

  <div class="container my-3">
    <section class="pb-3 col-lg-8 col-md-10 mx-auto mt-5">
      <div class="card bg-light">
        <div class="card-body">
          <h5 class="border-bottom pb-2 mt-5 mb-5">
            댓글 수정
          </h5>
          {% include 'form_errors.html' %}
          <form method="post">
            {% csrf_token %}
            <div class="form-group mb-3">
              <label for="content" class='mb-1'>댓글 내용</label>
              <textarea name='content' id='content' rows='10' class='form-control'>{{form.content.value}}</textarea>
            </div>
            <button type='submit' class='btn btn-secondary' style='float:right; background-color:#675444; color:#fff'>수정 완료</button>
          </form>
        </div>
      </div>
    </section>
  </div>
{% endblock contents %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="kor">

  <head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Petmily</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="shortcut icon" href="https://slack-imgs.com/?c=1&o1=ro&url=https%3A%2F%2Fcdn.pixabay.com%2Fphoto%2F2017%2F03%2F25%2F14%2F26%2Fanimals-2173635_960_720.jpg">
    {% block style %}{% endblock style %}
  </head>

  <body>
    {% include 'navbar.html' %}
    {% block contents %}{% endblock contents %}
    <footer></footer>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/navbar.js' %}"></script>
    <script>
      const tags = document.getElementsByTagName("body");
      for (const tag of tags) {
        if (localStorage.theme) {
          tag.setAttribute("data-bs-theme", localStorage.theme);
        }

        if (tag.getAttribute("data-bs-theme") == "dark") {
          document
            .querySelector(".bsc")
            .setAttribute("checked", "")
        }
        document
          .querySelector(".bsc")
          .addEventListener("change", () => {
            if (document.querySelector(".bsc").checked == true) {
              tag.setAttribute("data-bs-theme", "dark");
              localStorage.setItem("theme", "dark");
            } else {
              tag.setAttribute("data-bs-theme", "light");
              localStorage.setItem("theme", "light");
            }
          });
      }
    </script>
    {% block script %}{% endblock script %}
  </body>

</html>

templates/carousel.html
<div class="row justify-content-center">
  <div class="col-10">
    <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <div class="card mb-3 d-block">
            <img src="https://via.placeholder.com/1100X400" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <p class="card-text">
                <small class="text-muted">Last updated 3 mins ago</small>
              </p>
            </div>
          </div>
        </div>
        <div class="carousel-item">
          <div class="card mb-3 d-block">
            <img src="https://via.placeholder.com/1100X400" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <p class="card-text">
                <small class="text-muted">Last updated 3 mins ago</small>
              </p>
            </div>
          </div>
        </div>
        <div class="carousel-item">
          <div class="card mb-3 d-block">
            <img src="https://via.placeholder.com/1100X400" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <p class="card-text">
                <small class="text-muted">Last updated 3 mins ago</small>
              </p>
            </div>
          </div>
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>
</div>

templates/comment_form.html
{% extends 'base.html' %}
{% block contents %}
  <div class="container my-3">
    <section class="pb-3 col-lg-8 col-md-10 mx-auto mt-5">
      <div class="card bg-light">
        <div class="card-body">
          <h5 class="border-bottom pb-2 mt-5 mb-5">
            대댓글 등록
          </h5>
          {% include 'form_errors.html' %}
          <form method="post">
            {% csrf_token %}
            <div class="form-group mb-3">
              <label for="content" class='mb-1'>내용</label>
              <textarea name='content' id='content' rows='10' class='form-control'>{{form.content.value}}</textarea>
            </div>
            <button type='submit' class='btn btn-secondary' style='float:right; background-color:#675444; color:#fff'>대댓글 등록</button>
          </form>
        </div>
      </div>
    </section>
  </div>
{% endblock contents %}

templates/form_errors.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">
        <strong>{{field.label}}</strong>
        {{error}}
      </div>
    {% endfor %}
  {% endfor %}
{% endif %}
{% if form.non_field_errors %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{error}}
    </div>
  {% endfor %}
{% endif %}

templates/post_detail.html
{% extends 'base.html' %} {% load board_filter %} {% block style %}
<style>
  .bi-chat-square-heart {
    font-size: 30px;
    color: crimson;
  }

  {% comment %} .answer li {
    list-style: none;
  } {% endcomment %}

  .comment_create, .order {
    text-decoration: none;
    color: inherit;
  }
</style>
{% endblock style %} {% block contents %}
<div class="pt-3">
  <form class="col-lg-8 col-md-10 mx-auto">
    {% include 'form_errors.html' %}
    <div class="row mt-5 pt-3">
      <div class="row mt-3 mb-1">
        <div class="col-4">
          <h5 class="pb-2">
            <b>제목 : {{post.title}}</b>
          </h5>
        </div>
      </div>
      <hr class="one mb-3" />
      <div class="d-flex flex-row justify-content-between mb-5">
        <div class="py-2 text-muted">
          <!-- 작성날짜 -->
          <span>작성자 : {{post.writer}}</span>
          <span>({{post.created_at|date:'Y-m-d H:i'}})</span>
        </div>
        {% if post.modified_at %}
        <div class="pt-1">
          <div class="py-2 text-muted">
            <!-- 수정날짜 -->
            <div class="text-start">
              (수정 : {{post.modified_at|date:'Y-m-d H:i'}})
            </div>
          </div>
        </div>
        {% endif %}
      </div>
      <div class="col-12 mt-5 mb-5">
        {% if post.image %} {% for i in post.image.all %}
        <img
          src="{{i.image.url}}"
          alt=""
          class="mx-auto d-block"
          style="width: 600px"
        /><br />
        {% endfor %} {% endif %} {% comment %} {% if post.image %}
        <img src="{{post.image.url}}" alt="" class="mx-auto d-block" />
        {% endif %} {% endcomment %}
      </div>
      <div class="col-12 mb-5">
        <p>{{post.content}}</p>
      </div>
      <a href="#" data-uri="{% url 'vote_post' post.id %}" class="recommend btn mx-auto d-block"><i class="bi bi-chat-square-heart"></i></a>
      <hr class="one mt-5 mb-5" />

    </div>
    <div class="d-flex mb-5">
      <div class='me-auto'>
        {% if post.get_previous %}
        <div> 
          <a href="{{post.get_previous.get_absolute_url}}" class='order'>이전글 : {{post.get_previous}}</a>
        </div>
        {% endif %}
        {% if post.get_next %}
        <div> 
          <a href="{{post.get_next.get_absolute_url}}" class='order'>다음글 : {{post.get_next}}</a>
        </div>
        {% endif %}
      </div>
      <div>
        {% if post.writer == request.user %}
        <a href="#" class="btn btn-sm btn-outline-secondary delete" data-uri="{% url 'post_delete' post.id %}">삭제</a>
        <a href="{% url 'post_edit' post.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
        {% endif %}
        <a href="#" class="btn btn-sm btn-outline-secondary list" style="background-color:#675444; color:#fff" data-uri="{% url 'post_list' %}">목록으로</a>
      </div>
    </div>
  </form>
    <!-- 댓글 영역 -->
    <section class="pb-3 col-lg-8 col-md-10 mx-auto mb-5">
      <div class="card bg-light">
        <div class="card-body">
          <!-- 댓글 작성 폼 -->
          <h5 class="my-3 py-2">
            <!-- 댓글 개수 -->
            {{post.answer_set.count}} 개의 댓글이 있습니다.
          </h5>
          {% include 'form_errors.html' %}
          <div class="row mb-5">
            <form action="{% url 'answer_write' post.id %}" method="post">
              {% csrf_token %}
              <div class="form-group mb-3">
                <textarea name="content" id="content" rows="3" class="form-control"></textarea>
              </div>
              <button type="submit" class="btn btn-sm btn-outline-secondary" style="float: right">
                댓글 쓰기
              </button>
            </form>
          </div>
          {% comment %}
          <hr class="one mb-3" />
          {% endcomment %} {% for answer in post.answer_set.all %}
          <a name="answer_{{answer.id}}"></a>
          <div class="row">
            <div class="col-12 mb-3">
              <div class="border-top pt-3">
                <div>
                  <!-- 댓글 내용 -->
                  {{answer.content|mark}}
                </div>
                {% comment %} <div class="d-flex justify-content-end">
                  <div class="badge bg-secondary p-2">
                    <!-- 댓글 작성날짜 -->
                    작성 날짜 : {{answer.created_at|date:'Y-m-d H:i'}}
                  </div>
                </div>
                {% if answer.modified_at %}
                <div class="d-flex justify-content-end pt-1">
                  <div class="badge bg-secondary p-2">
                    <!-- 댓글 수정날짜 -->
                    <div class="text-start">
                      수정 : {{answer.modified_at|date:'Y-m-d H:i'}}
                    </div>
                  </div>
                </div>
                {% endif %} {% endcomment %}
                <div class='text-muted'>{{answer.writer}} {{answer.created_at|date:'Y-m-d H:i'}} (수정 : {{answer.modified_at|date:'Y-m-d H:i'}})</div>
                <div class="my-3">
                  {% if answer.writer == request.user %}
                  <a href="{% url 'answer_edit' answer.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
                  <a href="#" class="btn btn-sm btn-outline-secondary delete" data-uri="{% url 'answer_delete' answer.id %}">삭제</a>
                  {% endif %}
                  <a href="{% url 'comment_write' answer.id %}" class="btn btn-sm btn-outline-secondary">대댓글</a>
                  <a href="{% url 'vote_answer' answer.id %}" class="recommend btn btn-outline-secondary btn-sm ms-3">추천 : {{answer.vote.count}}</a>
                </div>
                <!-- 대댓글 -->
                {% if answer.comment_set.count > 0 %}
                <div class="mt-3 ms-5">
                  {% for comment in answer.comment_set.all %}
                  <!-- 앵커 부분 -->
                  <a name="comment_{{comment.id}}"></a>
                  <div class="comment py-2 text-muted">
                    <i class="bi bi-arrow-return-right"></i>
                    <span style="white-space: pre-line">{{comment.content}}</span>
                    <span>- {{comment.writer}} {{comment.created_at|date:'Y-m-d H:i'}} (수정 : {{comment.modified_at|date:'Y-m-d H:i'}})</span>
                    <!-- 대댓글 작성자와 로그인 사용자가 같다면 -->
                    {% if comment.writer == request.user %}
                    <a href="{% url 'comment_edit' comment.id %}" class="btn btn-sm btn-outline-secondary ms-3">수정</a>
                    <a href="#" data-uri="{% url 'comment_delete' comment.id %}" class="btn btn-sm btn-outline-secondary delete">삭제</a>
                    {% endif %}
                    <a href="{% url 'vote_comment' comment.id %}" class="recommend btn btn-outline-secondary btn-sm ms-3">추천 : {{comment.vote.count}}</a>
                  </div>
                  {% endfor %}
                </div>
                {% endif %}
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </section>
  
  <!-- 댓글 영역 종료 -->
</div>
{% endblock contents %} {% block script %}
<script>
  // 목록
  document
    .querySelector(".list")
    .addEventListener("click", () => (location.href = "{% url 'post_list' %}"));

  // 삭제
  let elements = document.querySelectorAll(".btn-danger, .delete");
  elements.forEach((ele, idx) => {
    ele.addEventListener("click", (e) => {
      if (confirm("정말로 삭제하시겠습니까?")) {
        location.href = e.target.dataset.uri;
      }
    });
  });

  // 추천 버튼 클릭 시 '정말로 추천하시겠습니까?'
  $(".recommend").on("click", function (e) {
    if (confirm("정말로 추천하시겠습니까?")) {
      location.href = $(this).data("uri");
    }
  });
</script>
{% endblock script %}

templates/post_edit.html
{% extends 'base.html' %}
{% block contents %}
  <div class="container">
    <h4 class="pb-2 mb-5 mt-5">
      글 수정
    </h4>
    {% include 'form_errors.html' %}
    <form method="post" class='row' enctype='multipart/form-data'>
      {% csrf_token %}
      <div class="form-group mb-5 col-6">
        <label for="title">제목</label>
        <input type="text" name='title' id='title' class='form-control mt-1' value="{{postForm.title.value}}">
      </div>
      <div class="form-group mb-5">
        <label for="content">내용</label>
        <textarea name='content' id='content' rows='13' class='form-control mt-1'>{{postForm.content.value}}</textarea>
      </div>
     
      <div>
        {{ formset.management_form }}
        {% for form in formset %}
            {{ form }}<br />
        {% endfor %}
      </div>
        
      {% comment %} <div class='d-flex'>
        <div class="form-group mb-5 col-3 ms-auto">
          <label for="image">사진첨부</label>
          <input type="file" name='image' id='image' class='form-control mt-1' value="{{form.image.value}}">
        </div>
      </div> {% endcomment %}
      
      <div class="text-center">
        <button type="submit" class="btn mt-2 mb-5" style="background-color:#675444; color:#fff">수정 완료</button>
      </div>
    </form>
  </div>
{% endblock contents %}

templates/post_list.html
{% extends 'base.html' %}
{% load board_filter %}
{% block style %}
<style>
  .list {
    text-decoration: none;
    color: inherit;
  }

  .fa-solid {
    color:#675444 ;
  }
</style>
<script src="https://kit.fontawesome.com/482f2e22f6.js" crossorigin="anonymous"></script>
{% endblock style %}
{% block contents %}
  <div class="container my-3 mb-5">
    <div class='pt-5'>
      <div class="d-flex justify-content-center mt-5 mb-5">
          <a href="{% url 'post_list' %}" class='list'><h1><i class="fa-solid fa-paw"></i> <strong>Community</strong> <i class="fa-solid fa-paw"></i></h1></a>
      </div>
      <hr style="width:40rem; margin: 0 auto;"/>

      <div class="d-flex justify-content-center mt-5 mb-5">
        {% if keyword %}
          <h5>'{{keyword}}' 검색 결과입니다.</h5>
        {% endif %}
      </div>
    </div>
    <div class="d-flex mt-5 mb-3">
      <!-- 정렬 -->
      <div class="col-1 me-auto">
        <select name="" id="so" class="form-control so text-center">
          <option value="recent" {% if so == 'recent' %}selected{% endif %}>최신순</option>
          <option value="recommend" {% if so == 'recommend' %}selected{% endif %}>추천순</option>
          <option value="popular" {% if so == 'popular' %}selected{% endif %}>인기순</option>
        </select>
      </div>
      <!-- 검색 -->
      <div class="col-1 me-2">
        <select name="" id="search_kind" class="form-control text-center">
          <option value="all" selected="selected">전체</option>
          <option value="title"{% if search_kind == 'title' %}selected{% endif %}>제목</option>
          <option value="writer"{% if search_kind == 'writer' %}selected{% endif %}>작성자</option>
          <option value="content"{% if search_kind == 'content' %}selected{% endif %}>내용</option>
        </select>
      </div>
      <div class="col-2 mb-3">
        <div class="input-group">
          <input onkeyup='enterkey()' type="text" name="keyword" id="keyword" class="form-control" value="{{keyword|default_if_none:''}}">
          <button type="button" class="btn btn-outline-secondary search">검색</button>
        </div>
      </div>
    </div>
    <!-- 테이블 -->
    <table class="table table-hover">
      <thead>
        <tr class="text-center">
          <th scope="col" style="width: 10%">no.</th>
          <th scope="col" style="width: 50%">제목</th>
          <th scope="col" style="width: 15%">작성자</th>
          <th scope="col" style="width: 15%">작성날짜</th>
          <th scope="col" style="width: 5%">조회</th>
          <th scope="col" style="width: 5%">추천</th>
        </tr>
      </thead>
      <tbody>
        {% if post_list %}
          {% for post in post_list %}
            <tr class="text-center">
              <td>
                {{post_list.paginator.count|sub:post_list.start_index|sub:forloop.counter0|add:1}}
              </td>
              <td class="title">
                <a href="{% url 'post_detail' post.id %}" class='move'>{{post.title}}
                  <span class='small m-2'>[{{post.answer_set.count}}]</span>
                </a>
              </td>
              <td>{{post.writer}}</td>
              <td>{{post.created_at|date:'Y-m-d H:i'}}</td>
              <td>{{post.view_cnt}}</td>
              <td>
                {% if post.vote.count %}
                  {{post.vote.count}}
                {% else %}
                  0
                  {% endif %}
              </td>
            </tr>
          {% endfor %}
        {% else %}
          {% if keyword %}
            <tr class='text-center'>
              <td colspan='5'>
                일치하는 검색 결과가 없습니다.
              </td>
            </tr>
          {% endif %}
        {% endif %}
      </tbody>
    </table>

    <div class="mt-3" style="float: right">
      <a href="{% url 'post_write' %}" class="btn" style="background-color:#675444; color:#fff">글 작성</a>
    </div>

    <!-- 페이징 -->
    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center">
        {% if post_list.has_previous %}
          <li class="page-item">
            <a class="page-link" href="#" data-page="{{post_list.previous_page_number}}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
        {% endif %}
        {% for page in post_list.paginator.page_range %}
          {% if page >= post_list.number|add:-5 and page <= post_list.number|add:5 %}
            <li class="page-item {% if page == post_list.number %}active{% endif %}">
              <a class="page-link" href="#" data-page="{{page}}">{{page}}</a>
            </li>
          {% endif %}
        {% endfor %}
        {% if post_list.has_next %}
          <li class="page-item">
            <a class="page-link" href="#" data-page="{{post_list.next_page_number}}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
        {% endif %}
      </ul>
    </nav>
  </div>

  <!-- 검색시 -->
  <form action="{% url 'post_list' %}" id='searchForm'>
    <input type="hidden" name='search_kind' value="{{search_kind|default_if_none:''}}" class='search_kind'>
    <input type="hidden" name='keyword' value="{{keyword|default_if_none:''}}" class='keyword'>
    <input type="hidden" name='page' value="{{page|default_if_none:''}}" id='page'>
    <input type="hidden" name='so' value="{{so|default_if_none:''}}" id='sort'>
  </form>

{% endblock contents %}

{% block script %}
  <script>
    const searchForm = document.querySelector('#searchForm');

    // 상세보기 - keyword, sort, page
    // searchForm
    const titles = document.querySelectorAll('.move')
    titles.forEach((title, idx) => {
      title.addEventListener('click', (e) => {
        e.preventDefault();
        searchForm.setAttribute('action', e.target.getAttribute('href'));

        searchForm.submit();
      })
    })

    // 하단의 1,2,3...페이지 클릭 시 searchForm 전송
    const pages = document.querySelectorAll('.page-link');
    pages.forEach((item, idx) => {
      item.addEventListener('click', (e) => {
        document
          .querySelector('#page')
          .value = e.target.dataset.page;

        searchForm.submit();
      })
    })

    // 정렬조건(so) change 되면
    // select 에서 선택된 값 가져온 후 searchForm 안에 sort 요소의 value 값으로 지정
    document.querySelector('#so').addEventListener('change', (e) => {
      document.querySelector('#sort').value = e.target.value;

      searchForm.submit();
    })

    // 검색버튼 클릭 -> 검색조건, 검색어 가져오기
    document.querySelector('.search').addEventListener('click', () => {
      let kind = document.querySelector('#search_kind').value;
      let keyword = document.querySelector('#keyword').value;

      // 검색조건, 검색어를 searchForm value 값으로 지정
      document.querySelector('.search_kind').value = kind;
      document.querySelector('.keyword').value = keyword;
      // searchForm 안의 page 요소의 값을 1로 지정
      document.querySelector('#page').value = 1;

      searchForm.submit();
    })

    // 엔터키 검색
    function enterkey() {
      if (window.event.keyCode == 13) {
        let kind = document.querySelector('#search_kind').value;
        let keyword = document.querySelector('#keyword').value;

        document.querySelector('.search_kind').value = kind;
        document.querySelector('.keyword').value = keyword;

        document.querySelector('#page').value = 1;

        searchForm.submit();
      }
    }
  </script>
{% endblock script %}